# Generated by Django 2.0.2 on 2018-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_url', models.URLField(max_length=500)),
                ('img', models.URLField(max_length=500)),
                ('scrape_object', models.CharField(max_length=100)),
                ('alert_url', models.URLField(max_length=500)),
                ('should_display', models.BooleanField(default=False)),
            ],
        ),
    ]
