# Generated by Django 2.0.2 on 2018-03-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alert',
            new_name='Alerts',
        ),
    ]
