# Generated by Django 2.0.2 on 2018-03-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180309_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='scrape_object',
            new_name='scraper_object',
        ),
    ]
