# Generated by Django 2.0.2 on 2018-03-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180310_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='scraper_object',
        ),
        migrations.AddField(
            model_name='alert',
            name='site_url',
            field=models.URLField(default='www.mangapanda.com', max_length=500),
            preserve_default=False,
        ),
    ]
